
package units_converter_program;

import java.text.DecimalFormat;

public class Currency_ConverterGUI extends javax.swing.JFrame {

    Currency_ERROR er_start = new Currency_ERROR();
    String[] CurrencyUnits = {
        "UNITS" , "Baht (THB)" ,  "Yen (JPY)" , "United State (USD)" , "United Kingdom (GBP)" , "European Union (EUR)" , "Australia (AUD)" 
        , "Switzerland (CHF)" , "China (CNY)" , "Malaysia (MYR)" , "Singapore (SGD)"
    };
    public Currency_ConverterGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_Fcountry = new javax.swing.JComboBox<>();
        jComboBox_Scountry = new javax.swing.JComboBox<>();
        in_TextField = new javax.swing.JTextField();
        re_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        convert_Button = new javax.swing.JButton();
        back_Button = new javax.swing.JButton();
        exit_Button = new javax.swing.JButton();
        sunits_Label = new javax.swing.JLabel();
        funits_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(679, 472));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel1.setText("Currency Units Converter");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(194, 194, 194))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBox_Fcountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "Thailand", "Japan", "United State", "United Kingdom", "European Union", "Australia", "Switzerland", "China", "Malaysia", "Singapore" }));
        jComboBox_Fcountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_FcountryItemStateChanged(evt);
            }
        });

        jComboBox_Scountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "Thailand", "Japan", "United State", "United Kingdom", "European Union", "Australia", "Switzerland", "China", "Malaysia", "Singapore" }));
        jComboBox_Scountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ScountryItemStateChanged(evt);
            }
        });

        re_TextField.setEditable(false);
        re_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                re_TextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        jLabel2.setText("RESULT :");

        jLabel3.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel3.setText("From currency of");

        jLabel4.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel4.setText("To currency of");

        convert_Button.setText("Converter");
        convert_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convert_ButtonActionPerformed(evt);
            }
        });

        back_Button.setText("Back");
        back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_ButtonActionPerformed(evt);
            }
        });

        exit_Button.setText("Exit");
        exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_ButtonActionPerformed(evt);
            }
        });

        sunits_Label.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        sunits_Label.setText("UNITS");

        funits_Label.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        funits_Label.setText("UNITS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sunits_Label))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(funits_Label)
                                    .addComponent(in_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(convert_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jComboBox_Scountry, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(exit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox_Fcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Fcountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Scountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(in_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sunits_Label)
                    .addComponent(funits_Label))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convert_Button)
                    .addComponent(back_Button)
                    .addComponent(exit_Button))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void re_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_re_TextFieldActionPerformed

    private void jComboBox_FcountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_FcountryItemStateChanged
        int position = jComboBox_Fcountry.getSelectedIndex();
        funits_Label.setText(CurrencyUnits[position]);
    }//GEN-LAST:event_jComboBox_FcountryItemStateChanged

    private void jComboBox_ScountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ScountryItemStateChanged
        int position = jComboBox_Scountry.getSelectedIndex();
        sunits_Label.setText(CurrencyUnits[position]);
    }//GEN-LAST:event_jComboBox_ScountryItemStateChanged

    private void convert_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convert_ButtonActionPerformed
        double in_value = Double.parseDouble(in_TextField.getText());
        double result = 0;
        
        if(jComboBox_Fcountry.getSelectedItem().toString() == "Thailand" && jComboBox_Scountry.getSelectedItem().toString() == "Thailand"){
            result = in_value;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Thailand" && jComboBox_Scountry.getSelectedItem().toString() == "Japan"){
            result = in_value * 3.379;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Thailand" && jComboBox_Scountry.getSelectedItem().toString() == "United State"){
            result = in_value * 0.032;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Thailand" && jComboBox_Scountry.getSelectedItem().toString() == "United Kingdom"){
            result = in_value * 0.025;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Thailand" && jComboBox_Scountry.getSelectedItem().toString() == "European Union"){
            result = in_value * 0.027;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Thailand" && jComboBox_Scountry.getSelectedItem().toString() == "Australia"){
            result = in_value * 0.044; 
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Thailand" && jComboBox_Scountry.getSelectedItem().toString() == "Switzerland"){
            result = in_value * 0.029;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Thailand" && jComboBox_Scountry.getSelectedItem().toString() == "China"){
            result = in_value * 0.217;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Thailand" && jComboBox_Scountry.getSelectedItem().toString() == "Malaysia"){
            result = in_value * 0.133;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Thailand" && jComboBox_Scountry.getSelectedItem().toString() == "Singapore"){
            result = in_value * 0.043;
        }
        
        else if(jComboBox_Fcountry.getSelectedItem().toString() == "Japan" && jComboBox_Scountry.getSelectedItem().toString() == "Thailand"){
            result = in_value * 0.296;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Japan" && jComboBox_Scountry.getSelectedItem().toString() == "Japan"){
            result = in_value;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Japan" && jComboBox_Scountry.getSelectedItem().toString() == "United State"){
            result = in_value * 0.009;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Japan" && jComboBox_Scountry.getSelectedItem().toString() == "United Kingdom"){
            result = in_value * 0.007;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Japan" && jComboBox_Scountry.getSelectedItem().toString() == "European Union"){
            result = in_value * 0.008;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Japan" && jComboBox_Scountry.getSelectedItem().toString() == "Australia"){
            result = in_value * 0.013;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Japan" && jComboBox_Scountry.getSelectedItem().toString() == "Switzerland"){
            result = in_value * 0.009;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Japan" && jComboBox_Scountry.getSelectedItem().toString() == "China"){
            result = in_value * 0.064;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Japan" && jComboBox_Scountry.getSelectedItem().toString() == "Malaysia"){
            result = in_value * 0.039;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Japan" && jComboBox_Scountry.getSelectedItem().toString() == "Singapore"){
            result = in_value * 0.013;
        }
        
        else if(jComboBox_Fcountry.getSelectedItem().toString() == "United State" && jComboBox_Scountry.getSelectedItem().toString() == "Thailand"){
            result = in_value * 31.290;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "United State" && jComboBox_Scountry.getSelectedItem().toString() == "Japan"){
            result = in_value * 105.734;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "United State" && jComboBox_Scountry.getSelectedItem().toString() == "United State"){
            result = in_value;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "United State" && jComboBox_Scountry.getSelectedItem().toString() == "United Kingdom"){
            result = in_value * 0.771;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "United State" && jComboBox_Scountry.getSelectedItem().toString() == "European Union"){
            result = in_value * 0.848;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "United State" && jComboBox_Scountry.getSelectedItem().toString() == "Australia"){
            result = in_value * 1.391;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "United State" && jComboBox_Scountry.getSelectedItem().toString() == "Switzerland"){
            result = in_value * 0.915;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "United State" && jComboBox_Scountry.getSelectedItem().toString() == "China"){
            result = in_value * 6.790;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "United State" && jComboBox_Scountry.getSelectedItem().toString() == "Malaysia"){
            result = in_value * 4.150;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "United State" && jComboBox_Scountry.getSelectedItem().toString() == "Singapore"){
            result = in_value * 1.360;
        }
        
        else if(jComboBox_Fcountry.getSelectedItem().toString() == "United Kingdom" && jComboBox_Scountry.getSelectedItem().toString() == "Thailand"){
            result = in_value * 40.606;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "United Kingdom" && jComboBox_Scountry.getSelectedItem().toString() == "Japan"){
            result = in_value * 137.215;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "United Kingdom" && jComboBox_Scountry.getSelectedItem().toString() == "United State"){
            result = in_value * 1.298;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "United Kingdom" && jComboBox_Scountry.getSelectedItem().toString() == "United Kingdom"){
            result = in_value;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "United Kingdom" && jComboBox_Scountry.getSelectedItem().toString() == "European Union"){
            result = in_value * 1.101;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "United Kingdom" && jComboBox_Scountry.getSelectedItem().toString() == "Australia"){
            result = in_value * 1.805;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "United Kingdom" && jComboBox_Scountry.getSelectedItem().toString() == "Switzerland"){
            result = in_value * 1.188;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "United Kingdom" && jComboBox_Scountry.getSelectedItem().toString() == "China"){
            result = in_value * 8.811;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "United Kingdom" && jComboBox_Scountry.getSelectedItem().toString() == "Malaysia"){
            result = in_value * 5.386;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "United Kingdom" && jComboBox_Scountry.getSelectedItem().toString() == "Singapore"){
            result = in_value * 1.765;
        }
        
        else if(jComboBox_Fcountry.getSelectedItem().toString() == "European Union" && jComboBox_Scountry.getSelectedItem().toString() == "Thailand"){
            result = in_value * 36.894;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "European Union" && jComboBox_Scountry.getSelectedItem().toString() == "Japan"){
            result = in_value * 124.672;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "European Union" && jComboBox_Scountry.getSelectedItem().toString() == "United State"){
            result = in_value * 1.179;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "European Union" && jComboBox_Scountry.getSelectedItem().toString() == "United Kingdom"){
            result = in_value * 0.909;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "European Union" && jComboBox_Scountry.getSelectedItem().toString() == "European Union"){
            result = in_value;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "European Union" && jComboBox_Scountry.getSelectedItem().toString() == "Australia"){
            result = in_value * 1.640;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "European Union" && jComboBox_Scountry.getSelectedItem().toString() == "Switzerland"){
            result = in_value * 1.079;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "European Union" && jComboBox_Scountry.getSelectedItem().toString() == "China"){
            result = in_value * 8.006;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "European Union" && jComboBox_Scountry.getSelectedItem().toString() == "Malaysia"){
            result = in_value * 4.893;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "European Union" && jComboBox_Scountry.getSelectedItem().toString() == "Singapore"){
            result = in_value * 1.604;
        }
        
        else if(jComboBox_Fcountry.getSelectedItem().toString() == "Australia" && jComboBox_Scountry.getSelectedItem().toString() == "Thailand"){
            result = in_value * 22.491;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Australia" && jComboBox_Scountry.getSelectedItem().toString() == "Japan"){
            result = in_value * 76.002;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Australia" && jComboBox_Scountry.getSelectedItem().toString() == "United State"){
            result = in_value * 0.719;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Australia" && jComboBox_Scountry.getSelectedItem().toString() == "United Kingdom"){
            result = in_value * 0.554;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Australia" && jComboBox_Scountry.getSelectedItem().toString() == "European Union"){
            result = in_value * 0.610;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Australia" && jComboBox_Scountry.getSelectedItem().toString() == "Australia"){
            result = in_value;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Australia" && jComboBox_Scountry.getSelectedItem().toString() == "Switzerland"){
            result = in_value * 0.658;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Australia" && jComboBox_Scountry.getSelectedItem().toString() == "China"){
            result = in_value * 4.881;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Australia" && jComboBox_Scountry.getSelectedItem().toString() == "Malaysia"){
            result = in_value * 2.983;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Australia" && jComboBox_Scountry.getSelectedItem().toString() == "Singapore"){
            result = in_value * 0.978;
        }
        
        else if(jComboBox_Fcountry.getSelectedItem().toString() == "Switzerland" && jComboBox_Scountry.getSelectedItem().toString() == "Thailand"){
            result = in_value * 34.178;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Switzerland" && jComboBox_Scountry.getSelectedItem().toString() == "Japan"){
            result = in_value * 115.494;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Switzerland" && jComboBox_Scountry.getSelectedItem().toString() == "United State"){
            result = in_value * 1.092;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Switzerland" && jComboBox_Scountry.getSelectedItem().toString() == "United Kingdom"){
            result = in_value * 0.842;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Switzerland" && jComboBox_Scountry.getSelectedItem().toString() == "European Union"){
            result = in_value * 0.926;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Switzerland" && jComboBox_Scountry.getSelectedItem().toString() == "Australia"){
            result = in_value * 1.520;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Switzerland" && jComboBox_Scountry.getSelectedItem().toString() == "Switzerland"){
            result = in_value;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Switzerland" && jComboBox_Scountry.getSelectedItem().toString() == "China"){
            result = in_value * 7.417;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Switzerland" && jComboBox_Scountry.getSelectedItem().toString() == "Malaysia"){
            result = in_value * 4.533;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Switzerland" && jComboBox_Scountry.getSelectedItem().toString() == "Singapore"){
            result = in_value * 1.486;
        }
        
        else if(jComboBox_Fcountry.getSelectedItem().toString() == "China" && jComboBox_Scountry.getSelectedItem().toString() == "Thailand"){
            result = in_value * 4.608;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "China" && jComboBox_Scountry.getSelectedItem().toString() == "Japan"){
            result = in_value * 15.572;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "China" && jComboBox_Scountry.getSelectedItem().toString() == "United State"){
            result = in_value * 0.147;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "China" && jComboBox_Scountry.getSelectedItem().toString() == "United Kingdom"){
            result = in_value * 0.113;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "China" && jComboBox_Scountry.getSelectedItem().toString() == "European Union"){
            result = in_value * 0.125;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "China" && jComboBox_Scountry.getSelectedItem().toString() == "Australian"){
            result = in_value * 0.205;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "China" && jComboBox_Scountry.getSelectedItem().toString() == "Switzerland"){
            result = in_value * 0.135;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "China" && jComboBox_Scountry.getSelectedItem().toString() == "China"){
            result = in_value;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "China" && jComboBox_Scountry.getSelectedItem().toString() == "Malaysia"){
            result = in_value * 0.611;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "China" && jComboBox_Scountry.getSelectedItem().toString() == "Singapore"){
            result = in_value * 0.200;
        }
        
        else if(jComboBox_Fcountry.getSelectedItem().toString() == "Malaysia" && jComboBox_Scountry.getSelectedItem().toString() == "Thailand"){
            result = in_value * 7.540;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Malaysia" && jComboBox_Scountry.getSelectedItem().toString() == "Japan"){
            result = in_value * 25.478;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Malaysia" && jComboBox_Scountry.getSelectedItem().toString() == "United State"){
            result = in_value * 0.241;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Malaysia" && jComboBox_Scountry.getSelectedItem().toString() == "United Kingdom"){
            result = in_value * 0.186;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Malaysia" && jComboBox_Scountry.getSelectedItem().toString() == "European Union"){
            result = in_value * 0.204;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Malaysia" && jComboBox_Scountry.getSelectedItem().toString() == "Australia"){
            result = in_value * 0.335;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Malaysia" && jComboBox_Scountry.getSelectedItem().toString() == "Switzerland"){
            result = in_value * 0.221;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Malaysia" && jComboBox_Scountry.getSelectedItem().toString() == "China"){
            result = in_value * 1.636;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Malaysia" && jComboBox_Scountry.getSelectedItem().toString() == "Malaysia"){
            result = in_value;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Malaysia" && jComboBox_Scountry.getSelectedItem().toString() == "Singapore"){
            result = in_value * 0.328;
        }
        
        else if(jComboBox_Fcountry.getSelectedItem().toString() == "Singapore" && jComboBox_Scountry.getSelectedItem().toString() == "Thailand"){
            result = in_value * 23.003;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Singapore" && jComboBox_Scountry.getSelectedItem().toString() == "Japan"){
            result = in_value * 77.730;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Singapore" && jComboBox_Scountry.getSelectedItem().toString() == "United State"){
            result = in_value * 0.735;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Singapore" && jComboBox_Scountry.getSelectedItem().toString() == "United Kingdom"){
            result = in_value * 0.566;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Singapore" && jComboBox_Scountry.getSelectedItem().toString() == "European Union"){
            result = in_value * 0.623;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Singapore" && jComboBox_Scountry.getSelectedItem().toString() == "Australia"){
            result = in_value * 1.023;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Singapore" && jComboBox_Scountry.getSelectedItem().toString() == "Switzerland"){
            result = in_value * 0.673;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Singapore" && jComboBox_Scountry.getSelectedItem().toString() == "China"){
            result = in_value * 4.991;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Singapore" && jComboBox_Scountry.getSelectedItem().toString() == "Malaysia"){
            result = in_value * 3.051;
        }else if(jComboBox_Fcountry.getSelectedItem().toString() == "Singapore" && jComboBox_Scountry.getSelectedItem().toString() == "Singapore"){
            result = in_value;
        }else{
            System.out.println("ERROR - PLEASE RESTART THE PROGRAM");
            er_start.setVisible(true);
            er_start.setVisible(true);
        }
        
        re_TextField.setText(new DecimalFormat("0.000").format(result));
    }//GEN-LAST:event_convert_ButtonActionPerformed

    private void back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_ButtonActionPerformed
        MainGUI goback = new MainGUI();
        goback.setVisible(true);
        goback.setAlwaysOnTop(true);
    }//GEN-LAST:event_back_ButtonActionPerformed

    private void exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_ButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Currency_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Currency_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Currency_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Currency_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Currency_ConverterGUI().setVisible(true);
                new Currency_ConverterGUI().setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_Button;
    private javax.swing.JButton convert_Button;
    private javax.swing.JButton exit_Button;
    private javax.swing.JLabel funits_Label;
    private javax.swing.JTextField in_TextField;
    private javax.swing.JComboBox<String> jComboBox_Fcountry;
    private javax.swing.JComboBox<String> jComboBox_Scountry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField re_TextField;
    private javax.swing.JLabel sunits_Label;
    // End of variables declaration//GEN-END:variables
}
