/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package units_converter_program;

import java.text.DecimalFormat;
import java.text.NumberFormat;

/**
 *
 * @author Surachai
 */
public class DigitalStorage_ConverterGUI extends javax.swing.JFrame {

    DigitalStorage_ERROR  er_start = new DigitalStorage_ERROR();
    NumberFormat num_format = new DecimalFormat();
    
    String[] digitalSto_units = {
      "UNITS" , "Bit" , "Byte" , "Kilobyte" , "Megabyte" , "Gigabyte" , "Terabyte" , "Petabyte"
    };
    
    String[] digitalSto_formular = {
        "None" ,                                           //0
        "None" ,                                           //1
        "Divide the digital storage value by 8" ,          //2
        "Divide the digital storage value by 8000" ,       //3
        "Divide the digital storage value by 8e+6" ,       //4
        "Divide the digital storage value by 8e+9",        //5
        "Divide the digital storage value by 8e+12",       //6
        "Divide the digital storage value by 8e+15",       //7
        
        "None" ,                                           //8
        "Multiply the digital storage value by 8" ,        //9
        "None" ,                                           //10
        "Divide the digital storage value by 1000" ,       //11
        "Divide the digital storage value by 1e+6" ,       //12
        "Divide the digital storage value by 1e+9",        //13
        "Divide the digital storage value by 1e+12",       //14
        "Divide the digital storage value by 1e+15",       //15
        
        "None" ,                                           //16
        "Multiply the digital storage value by 8000" ,     //17
        "Multiply the digital storage value by 1000" ,     //18
        "None" ,                                           //19
        "Divide the digital storage value by 1000" ,       //20
        "Divide the digital storage value by 1e+6",        //21
        "Divide the digital storage value by 1e+9",        //22
        "Divide the digital storage value by 1e+12",       //23
        
        "None" ,                                           //24
        "Multiply the digital storage value by 8e+6" ,     //25
        "Multiply the digital storage value by 1e+6" ,     //26
        "Multiply the digital storage value by 1000" ,     //27
        "None" ,                                           //28
        "Divide the digital storage value by 1000",        //29
        "Divide the digital storage value by 1e+6",        //30
        "Divide the digital storage value by 1e+9",        //31
        
        "None",                                            //32
        "Multiply the digital storage value by 8e+9",      //33
        "Multiply the digital storage value by 1e+9",      //34
        "Multiply the digital storage value by 1e+6",      //35
        "Multiply the digital storage value by 1000",      //36
        "None",                                            //37
        "Divide the digital storage value by 1000",        //38
        "Divide the digital storage value by 1e+6",        //39
        
        "None",                                            //40
        "Multiply the digital storage value by 8e+12",     //41
        "Multiply the digital storage value by 1e+12",     //42
        "Multiply the digital storage value by 1e+9",      //43
        "Multiply the digital storage value by 1e+6",      //44
        "Multiply the digital storage value by 1000",      //45
        "None",                                            //46
        "Divide the digital storage value by 1000",        //47
        
        "None",                                            //48
        "Multiply the digital storage value by 8e+15",     //49
        "Multiply the digital storage value by 1e+15",     //50
        "Multiply the digital storage value by 1e+12",     //51
        "Multiply the digital storage value by 1e+9",      //52
        "Multiply the digital storage value by 1e+6",      //53
        "Multiply the digital storage value by 1000",      //54
        "None",                                            //55
        "None",                                            //56
        
    };
    public DigitalStorage_ConverterGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_Funits = new javax.swing.JComboBox<>();
        jComboBox_Sunits = new javax.swing.JComboBox<>();
        in_TextField = new javax.swing.JTextField();
        re_TextField = new javax.swing.JTextField();
        funits_Label = new javax.swing.JLabel();
        sunits_Label = new javax.swing.JLabel();
        back_Button = new javax.swing.JButton();
        exit_Button = new javax.swing.JButton();
        convert_Button = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        formular_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel1.setText("Digital Storage Units Converter");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(181, 181, 181))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        jLabel3.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel3.setText("From digital unit of");

        jLabel4.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel4.setText("To digital unit of");

        jComboBox_Funits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "Bit", "Byte", "Kilobyte", "Megabyte", "Gigabyte", "Terabyte", "Petabyte", " " }));
        jComboBox_Funits.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_FunitsItemStateChanged(evt);
            }
        });

        jComboBox_Sunits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "Bit", "Byte", "Kilobyte", "Megabyte", "Gigabyte", "Terabyte", "Petabyte" }));
        jComboBox_Sunits.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_SunitsItemStateChanged(evt);
            }
        });

        funits_Label.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        funits_Label.setText("UNITS");

        sunits_Label.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        sunits_Label.setText("UNITS");

        back_Button.setText("Back");
        back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_ButtonActionPerformed(evt);
            }
        });

        exit_Button.setText("Exit");
        exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_ButtonActionPerformed(evt);
            }
        });

        convert_Button.setText("Converter");
        convert_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convert_ButtonActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.lightGray, null, java.awt.Color.lightGray));

        jLabel5.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        jLabel5.setText("FORMULAR :");

        formular_Label.setFont(new java.awt.Font("SimSun", 0, 16)); // NOI18N
        formular_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formular_Label.setText("FORMULAR");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(321, Short.MAX_VALUE))
            .addComponent(formular_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(formular_Label)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(funits_Label)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jComboBox_Funits, 0, 200, Short.MAX_VALUE)
                        .addComponent(in_TextField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox_Sunits, 0, 200, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(re_TextField))
                    .addComponent(sunits_Label, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(convert_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(exit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Funits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Sunits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funits_Label)
                    .addComponent(sunits_Label))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_Button)
                    .addComponent(convert_Button)
                    .addComponent(exit_Button))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_ButtonActionPerformed
        MainGUI goback = new MainGUI();
        goback.setVisible(true);
        goback.setAlwaysOnTop(true);
    }//GEN-LAST:event_back_ButtonActionPerformed

    private void exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_ButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit_ButtonActionPerformed

    private void convert_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convert_ButtonActionPerformed
        
        double in_value = Double.parseDouble(in_TextField.getText());
        double result = 0;

        if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Bit"){
            result = in_value;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Byte"){
            result = in_value / 8;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Kilobyte"){
            result = in_value / 8000;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Megabyte"){
            result = in_value / 8e+6;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Gigabyte"){
            result = in_value / 8e+9;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            result = in_value / 8e+12;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Petabyte"){
            result = in_value / 8e+15;
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Bit"){
            result = in_value * 8;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Byte"){
            result = in_value;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Kilobyte"){
            result = in_value / 1000;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Megabyte"){
            result = in_value / 1e+6;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Gigabyte"){
            result = in_value / 1e+9;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            result = in_value / 1e+12;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Petabyte"){
            result = in_value / 1e+15;
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Bit"){
            result = in_value * 8000;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Byte"){
            result = in_value * 1000;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Kilobyte"){
            result = in_value;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Megabyte"){
            result = in_value / 1000;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Gigabyte"){
            result = in_value / 1e+6; 
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            result = in_value / 1e+9;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Petabyte"){
            result = in_value / 1e+12;
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Bit"){
            result = in_value * 8e+6;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Byte"){
            result = in_value * 1e+6;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Kilobyte"){
            result = in_value * 1000;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Megabyte"){
            result = in_value;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Gigabyte"){
            result = in_value / 1000;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            result = in_value / 1e+6;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Petabyte"){
            result = in_value / 1e+9;
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Bit"){
            result = in_value * 8e+9;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Byte"){
            result = in_value * 1e+9;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Kilobyte"){
            result = in_value * 1e+6;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Megabyte"){
            result = in_value * 1000;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Gigabyte"){
            result = in_value;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            result = in_value / 1000;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Petabyte"){
            result = in_value / 1e+6;
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Bit"){
            result = in_value * 8e+12;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Byte"){
            result = in_value * 1e+12;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Kilobyte"){
            result = in_value * 1e+9;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Megabyte"){
            result = in_value * 1e+6;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Gigabyte"){
            result = in_value * 1000;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            result = in_value;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Petabyte"){
            result = in_value / 1000;
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            result = in_value * 8e+15;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            result = in_value * 1e+15;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            result = in_value * 1e+12;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            result = in_value * 1e+9;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            result = in_value * 1e+6;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            result = in_value * 1000;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            result = in_value;
        }else{
             System.out.println("ERROR - PLEASE RESTART THE PROGRAM");
             er_start.setAlwaysOnTop(true);
             er_start.setVisible(true);
        }
        
       
        re_TextField.setText(new DecimalFormat("0.000").format(result));
    }//GEN-LAST:event_convert_ButtonActionPerformed

    private void jComboBox_FunitsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_FunitsItemStateChanged
       int position = jComboBox_Funits.getSelectedIndex();
       funits_Label.setText(digitalSto_units[position]);
       
        if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
            formular_Label.setText(digitalSto_formular[0]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Bit"){
            formular_Label.setText(digitalSto_formular[1]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Byte"){
            formular_Label.setText(digitalSto_formular[2]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Kilobyte"){
            formular_Label.setText(digitalSto_formular[3]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Megabyte"){
            formular_Label.setText(digitalSto_formular[4]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Gigabyte"){
            formular_Label.setText(digitalSto_formular[5]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[6]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Petabyte"){
            formular_Label.setText(digitalSto_formular[7]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
            formular_Label.setText(digitalSto_formular[8]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Bit"){
            formular_Label.setText(digitalSto_formular[9]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Byte"){
            formular_Label.setText(digitalSto_formular[10]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Kilobyte"){
            formular_Label.setText(digitalSto_formular[11]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Megabyte"){
            formular_Label.setText(digitalSto_formular[12]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Gigabyte"){
            formular_Label.setText(digitalSto_formular[13]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[14]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Petabyte"){
            formular_Label.setText(digitalSto_formular[15]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
            formular_Label.setText(digitalSto_formular[16]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Bit"){
            formular_Label.setText(digitalSto_formular[17]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Byte"){
            formular_Label.setText(digitalSto_formular[18]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Kilobyte"){
            formular_Label.setText(digitalSto_formular[19]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Megabyte"){
            formular_Label.setText(digitalSto_formular[20]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Gigabyte"){
            formular_Label.setText(digitalSto_formular[21]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[22]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Petabyte"){
            formular_Label.setText(digitalSto_formular[23]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
            formular_Label.setText(digitalSto_formular[24]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Bit"){
            formular_Label.setText(digitalSto_formular[25]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Byte"){
            formular_Label.setText(digitalSto_formular[26]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Kilobyte"){
            formular_Label.setText(digitalSto_formular[27]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Megabyte"){
            formular_Label.setText(digitalSto_formular[28]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Gigabyte"){
            formular_Label.setText(digitalSto_formular[29]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[30]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Petabyte"){
            formular_Label.setText(digitalSto_formular[31]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
            formular_Label.setText(digitalSto_formular[32]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Bit"){
            formular_Label.setText(digitalSto_formular[33]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Byte"){
            formular_Label.setText(digitalSto_formular[34]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Kilobyte"){
            formular_Label.setText(digitalSto_formular[35]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Megabyte"){
            formular_Label.setText(digitalSto_formular[36]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Gigabyte"){
            formular_Label.setText(digitalSto_formular[37]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[38]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Petabyte"){
            formular_Label.setText(digitalSto_formular[39]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
            formular_Label.setText(digitalSto_formular[40]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Bit"){
            formular_Label.setText(digitalSto_formular[41]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Byte"){
            formular_Label.setText(digitalSto_formular[42]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Kilobyte"){
            formular_Label.setText(digitalSto_formular[43]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Megabyte"){
            formular_Label.setText(digitalSto_formular[44]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Gigabyte"){
            formular_Label.setText(digitalSto_formular[45]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[46]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Petabyte"){
            formular_Label.setText(digitalSto_formular[47]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
            formular_Label.setText(digitalSto_formular[48]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[49]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[50]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[51]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[52]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[53]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[54]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[55]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[56]);
        }
       
    }//GEN-LAST:event_jComboBox_FunitsItemStateChanged

    private void jComboBox_SunitsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_SunitsItemStateChanged
       int position = jComboBox_Sunits.getSelectedIndex();
       sunits_Label.setText(digitalSto_units[position]);
       
        if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Bit"){
            formular_Label.setText(digitalSto_formular[0]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Bit"){
            formular_Label.setText(digitalSto_formular[1]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Byte"){
            formular_Label.setText(digitalSto_formular[2]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Kilobyte"){
            formular_Label.setText(digitalSto_formular[3]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Megabyte"){
            formular_Label.setText(digitalSto_formular[4]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Gigabyte"){
            formular_Label.setText(digitalSto_formular[5]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[6]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Bit" && jComboBox_Sunits.getSelectedItem().toString() == "Petabyte"){
            formular_Label.setText(digitalSto_formular[7]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Byte"){
            formular_Label.setText(digitalSto_formular[8]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Bit"){
            formular_Label.setText(digitalSto_formular[9]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Byte"){
            formular_Label.setText(digitalSto_formular[10]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Kilobyte"){
            formular_Label.setText(digitalSto_formular[11]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Megabyte"){
            formular_Label.setText(digitalSto_formular[12]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Gigabyte"){
            formular_Label.setText(digitalSto_formular[13]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[14]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Byte" && jComboBox_Sunits.getSelectedItem().toString() == "Petabyte"){
            formular_Label.setText(digitalSto_formular[15]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Kilobyte"){
            formular_Label.setText(digitalSto_formular[16]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Bit"){
            formular_Label.setText(digitalSto_formular[17]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Byte"){
            formular_Label.setText(digitalSto_formular[18]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Kilobyte"){
            formular_Label.setText(digitalSto_formular[19]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Megabyte"){
            formular_Label.setText(digitalSto_formular[20]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Gigabyte"){
            formular_Label.setText(digitalSto_formular[21]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[22]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kilobyte" && jComboBox_Sunits.getSelectedItem().toString() == "Petabyte"){
            formular_Label.setText(digitalSto_formular[23]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Megabyte"){
            formular_Label.setText(digitalSto_formular[24]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Bit"){
            formular_Label.setText(digitalSto_formular[25]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Byte"){
            formular_Label.setText(digitalSto_formular[26]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Kilobyte"){
            formular_Label.setText(digitalSto_formular[27]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Megabyte"){
            formular_Label.setText(digitalSto_formular[28]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Gigabyte"){
            formular_Label.setText(digitalSto_formular[29]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[30]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Megabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Petabyte"){
            formular_Label.setText(digitalSto_formular[31]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Gigabyte"){
            formular_Label.setText(digitalSto_formular[32]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Bit"){
            formular_Label.setText(digitalSto_formular[33]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Byte"){
            formular_Label.setText(digitalSto_formular[34]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Kilobyte"){
            formular_Label.setText(digitalSto_formular[35]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Megabyte"){
            formular_Label.setText(digitalSto_formular[36]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Gigabyte"){
            formular_Label.setText(digitalSto_formular[37]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[38]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Gigabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Petabyte"){
            formular_Label.setText(digitalSto_formular[39]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[40]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Bit"){
            formular_Label.setText(digitalSto_formular[41]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Byte"){
            formular_Label.setText(digitalSto_formular[42]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Kilobyte"){
            formular_Label.setText(digitalSto_formular[43]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Megabyte"){
            formular_Label.setText(digitalSto_formular[44]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Gigabyte"){
            formular_Label.setText(digitalSto_formular[45]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[46]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Terabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Petabyte"){
            formular_Label.setText(digitalSto_formular[47]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Petabyte"){
            formular_Label.setText(digitalSto_formular[48]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[49]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[50]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[51]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[52]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[53]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[54]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Petabyte" && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[55]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Terabyte"){
            formular_Label.setText(digitalSto_formular[56]);
        }
    }//GEN-LAST:event_jComboBox_SunitsItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DigitalStorage_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DigitalStorage_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DigitalStorage_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DigitalStorage_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DigitalStorage_ConverterGUI().setVisible(true);
                new DigitalStorage_ConverterGUI().setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_Button;
    private javax.swing.JButton convert_Button;
    private javax.swing.JButton exit_Button;
    private javax.swing.JLabel formular_Label;
    private javax.swing.JLabel funits_Label;
    private javax.swing.JTextField in_TextField;
    private javax.swing.JComboBox<String> jComboBox_Funits;
    private javax.swing.JComboBox<String> jComboBox_Sunits;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField re_TextField;
    private javax.swing.JLabel sunits_Label;
    // End of variables declaration//GEN-END:variables
}
