/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package units_converter_program;

import java.text.DecimalFormat;

/**
 *
 * @author Surachai
 */
public class Temp_ConverterGUI extends javax.swing.JFrame {

    Temp_ERROR er_start = new Temp_ERROR();
    String[] temp_units = {
        "UNITS" , "Celsius (°C)" , "Fahrenheit (°F)" , "Kelvin (K)"
    };
    
    String[] temp_formular = {
            "None" ,                        //0
            "None" ,                        //1  
            "(°C * 9/5) + 32" ,             //2
            "°C + 273.15" ,                 //3
            
            "None",                         //4
            "(°F - 32 ) * 5/9" ,            //5
            "None" ,                        //6
            "(°F - 32) * 5/9 + 273.15" ,    //7
            
            "None" ,                        //8
            "K - 273.15" ,                  //9
            "(K - 273.15) * 9/5 + 32" ,     //10
            "None" ,                        //11
            "None"                          //12
    };
    public Temp_ConverterGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_Funits = new javax.swing.JComboBox<>();
        jComboBox_Sunits = new javax.swing.JComboBox<>();
        in_TextField = new javax.swing.JTextField();
        re_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        funits_Label = new javax.swing.JLabel();
        sunits_Label = new javax.swing.JLabel();
        back_Button = new javax.swing.JButton();
        exit_Button = new javax.swing.JButton();
        convert_Button = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        formular_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel1.setText("Temperature Units Converter");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(160, 160, 160))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBox_Funits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "Celsius", "Fahrenheit", "Kelvin" }));
        jComboBox_Funits.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_FunitsItemStateChanged(evt);
            }
        });

        jComboBox_Sunits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "Celsius", "Fahrenheit", "Kelvin" }));
        jComboBox_Sunits.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_SunitsItemStateChanged(evt);
            }
        });

        re_TextField.setEditable(false);

        jLabel2.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        jLabel2.setText("RESULT :");

        jLabel3.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel3.setText("From temperature unit of");

        jLabel4.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel4.setText("To temperature unit of");

        funits_Label.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        funits_Label.setText("UNITS");

        sunits_Label.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        sunits_Label.setText("UNITS");

        back_Button.setText("Back");
        back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_ButtonActionPerformed(evt);
            }
        });

        exit_Button.setText("Exit");
        exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_ButtonActionPerformed(evt);
            }
        });

        convert_Button.setText("Converter");
        convert_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convert_ButtonActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.lightGray, null, java.awt.Color.lightGray));

        jLabel5.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        jLabel5.setText("FORMULAR :");

        formular_Label.setFont(new java.awt.Font("SimSun", 0, 16)); // NOI18N
        formular_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formular_Label.setText("FORMULAR");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(262, Short.MAX_VALUE))
            .addComponent(formular_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(formular_Label)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(funits_Label)
                                    .addComponent(in_TextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_Funits, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox_Sunits, 0, 200, Short.MAX_VALUE)
                                .addComponent(re_TextField))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sunits_Label)))
                .addGap(35, 35, 35))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(convert_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(exit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Funits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Sunits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funits_Label)
                    .addComponent(sunits_Label))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(convert_Button)
                            .addComponent(back_Button)
                            .addComponent(exit_Button))
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_ButtonActionPerformed
        MainGUI goback = new MainGUI();
        goback.setVisible(true);
        goback.setAlwaysOnTop(true);
    }//GEN-LAST:event_back_ButtonActionPerformed

    private void exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_ButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit_ButtonActionPerformed

    private void convert_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convert_ButtonActionPerformed
        double in_value = Double.parseDouble(in_TextField.getText());
        double result = 0;
        
        if(jComboBox_Funits.getSelectedItem().toString() == "Celsius" && jComboBox_Sunits.getSelectedItem().toString() == "Celsius"){
            result = in_value;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Celsius" && jComboBox_Sunits.getSelectedItem().toString() == "Fahrenheit"){
            result = (in_value * 9/5) + 32;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Celsius" && jComboBox_Sunits.getSelectedItem().toString() == "Kelvin"){
            result = in_value + 273.15;
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Fahrenheit" && jComboBox_Sunits.getSelectedItem().toString() == "Celsius"){
            result = (in_value - 32) * 5/9;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Fahrenheit" && jComboBox_Sunits.getSelectedItem().toString() == "Fahrenheit"){
            result = in_value;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Fahrenheit" && jComboBox_Sunits.getSelectedItem().toString() == "Kelvin"){
            result = (in_value - 32) * 5/9 + 273.15;
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Kelvin" && jComboBox_Sunits.getSelectedItem().toString() == "Celsius"){
            result = in_value - 273.15;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kelvin" && jComboBox_Sunits.getSelectedItem().toString() == "Fahrenheit"){
            result = (in_value - 273.15) * 9/5 + 32;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kelvin" && jComboBox_Sunits.getSelectedItem().toString() == "Kelvin"){
            result = in_value;
        }else{
             System.out.println("ERROR - PLEASE RESTART THE PROGRAM");
             er_start.setAlwaysOnTop(true);
             er_start.setVisible(true);
        }
               
        re_TextField.setText(new DecimalFormat("0.000").format(result));
    }//GEN-LAST:event_convert_ButtonActionPerformed

    private void jComboBox_FunitsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_FunitsItemStateChanged
        int position = jComboBox_Funits.getSelectedIndex();
        funits_Label.setText(temp_units[position]);
        
        if(jComboBox_Funits.getSelectedItem().toString() == "Celsius" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
            formular_Label.setText(temp_formular[0]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Celsius" && jComboBox_Sunits.getSelectedItem().toString() == "Celsius"){
            formular_Label.setText(temp_formular[1]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Celsius" && jComboBox_Sunits.getSelectedItem().toString() == "Fahrenheit"){
            formular_Label.setText(temp_formular[2]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Celsius" && jComboBox_Sunits.getSelectedItem().toString() == "Kelvin"){
            formular_Label.setText(temp_formular[3]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Fahrenheit" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
            formular_Label.setText(temp_formular[4]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Fahrenheit" && jComboBox_Sunits.getSelectedItem().toString() == "Celsius"){
            formular_Label.setText(temp_formular[5]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Fahrenheit" && jComboBox_Sunits.getSelectedItem().toString() == "Fahrenheit"){
            formular_Label.setText(temp_formular[6]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Fahrenheit" && jComboBox_Sunits.getSelectedItem().toString() == "Kelvin"){
            formular_Label.setText(temp_formular[7]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Kelvin" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
            formular_Label.setText(temp_formular[8]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kelvin" && jComboBox_Sunits.getSelectedItem().toString() == "Celsius"){
            formular_Label.setText(temp_formular[9]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kelvin" && jComboBox_Sunits.getSelectedItem().toString() == "Fahrenheit"){
            formular_Label.setText(temp_formular[10]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kelvin" && jComboBox_Sunits.getSelectedItem().toString() == "Kelvin"){
            formular_Label.setText(temp_formular[11]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
            formular_Label.setText(temp_formular[12]);
        }
    }//GEN-LAST:event_jComboBox_FunitsItemStateChanged

    private void jComboBox_SunitsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_SunitsItemStateChanged
        int position = jComboBox_Sunits.getSelectedIndex();
        sunits_Label.setText(temp_units[position]);
        
         if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Celsius"){
            formular_Label.setText(temp_formular[0]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Celsius" && jComboBox_Sunits.getSelectedItem().toString() == "Celsius"){
            formular_Label.setText(temp_formular[1]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Celsius" && jComboBox_Sunits.getSelectedItem().toString() == "Fahrenheit"){
            formular_Label.setText(temp_formular[2]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Celsius" && jComboBox_Sunits.getSelectedItem().toString() == "Kelvin"){
            formular_Label.setText(temp_formular[3]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Fahrenheit"){
            formular_Label.setText(temp_formular[4]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Fahrenheit" && jComboBox_Sunits.getSelectedItem().toString() == "Celsius"){
            formular_Label.setText(temp_formular[5]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Fahrenheit" && jComboBox_Sunits.getSelectedItem().toString() == "Fahrenheit"){
            formular_Label.setText(temp_formular[6]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Fahrenheit" && jComboBox_Sunits.getSelectedItem().toString() == "Kelvin"){
            formular_Label.setText(temp_formular[7]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Kelvin"){
            formular_Label.setText(temp_formular[8]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kelvin" && jComboBox_Sunits.getSelectedItem().toString() == "Celsius"){
            formular_Label.setText(temp_formular[9]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kelvin" && jComboBox_Sunits.getSelectedItem().toString() == "Fahrenheit"){
            formular_Label.setText(temp_formular[10]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Kelvin" && jComboBox_Sunits.getSelectedItem().toString() == "Kelvin"){
            formular_Label.setText(temp_formular[11]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
            formular_Label.setText(temp_formular[12]);
        }
         
    }//GEN-LAST:event_jComboBox_SunitsItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temp_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temp_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temp_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temp_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temp_ConverterGUI().setVisible(true);
                new Temp_ConverterGUI().setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_Button;
    private javax.swing.JButton convert_Button;
    private javax.swing.JButton exit_Button;
    private javax.swing.JLabel formular_Label;
    private javax.swing.JLabel funits_Label;
    private javax.swing.JTextField in_TextField;
    private javax.swing.JComboBox<String> jComboBox_Funits;
    private javax.swing.JComboBox<String> jComboBox_Sunits;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField re_TextField;
    private javax.swing.JLabel sunits_Label;
    // End of variables declaration//GEN-END:variables
}
