/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package units_converter_program;

import java.text.DecimalFormat;

/**
 *
 * @author Surachai
 */
public class Time_ConverterGUI extends javax.swing.JFrame {

    Time_ERROR er_start = new Time_ERROR();
    String[] time_units = {
      "UNITS" , "Second (s.)" , "Minute (min.)" , "Hour (hr.)" , "Day" , "Week" , "Month"
    };
    
    String[] time_formular = {
        "None",                                                    //0
        "None",                                                    //1
        "Divide the time value by 60",                             //2
        "Divide the time value by 3600",                           //3
        "Divide the time value by 86400",                          //4
        "Divide the time value by 604800",                         //5
        "Divide the time value by 2.628e+6",                       //6
        
        "None",                                                    //7
        "Multiply the time value by 60",                           //8
        "None",                                                    //9
        "Divide the time value by 60",                             //10
        "Divide the time value by 1440",                           //11
        "Divide the time value by 10080",                          //12
        "Divide the time value by 43800",                          //13
        
        "None",                                                    //14
        "Multiply the time value by 3600",                         //15
        "Multiply the time value by 60",                           //16
        "None",                                                    //17
        "Divide the time value by 24",                             //18
        "Divide the time value by 168",                            //19
        "Divide the time value by 730",                            //20
        
        "None",                                                    //21
        "Multiply the time value by 86400",                        //22
        "Multiply the time value by 1440",                         //23
        "Multiply the time value by 24",                           //24
        "None",                                                    //25
        "Divide the time value by 7",                              //26
        "Divide the time value by 30.417",                         //27
        
        "None",                                                    //28
        "Multiply the time value by 604800",                       //29
        "Multiply the time value by 10080",                        //30                                  
        "Multiply the time value by 168",                          //31
        "Multiply the time value by 7",                            //32     
        "None",                                                    //33
        "Divide the time value by 4.345",                          //34
    
        "None",                                                    //35
        "Multiply the time value by 2.628e+6",                     //36
        "Multiply the time value by 43800",                        //37
        "Multiply the time value by 730",                          //38
        "Multiply the time value by 30.417",                       //39
        "Multiply the time value by 4.345",                        //40
        "None"                                                     //41
    
    };
   
    public Time_ConverterGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_Funits = new javax.swing.JComboBox<>();
        jComboBox_Sunits = new javax.swing.JComboBox<>();
        in_TextField = new javax.swing.JTextField();
        re_TextField = new javax.swing.JTextField();
        funits_Label = new javax.swing.JLabel();
        sunits_Label = new javax.swing.JLabel();
        back_Button = new javax.swing.JButton();
        exit_Button = new javax.swing.JButton();
        convert_Button = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        formular_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel1.setText("Time Units Converter");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(222, 222, 222))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        jLabel3.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel3.setText("From time unit of");

        jLabel4.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel4.setText("To time unit of");

        jComboBox_Funits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "Second", "Minute", "Hour", "Day", "Week", "Month" }));
        jComboBox_Funits.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_FunitsItemStateChanged(evt);
            }
        });

        jComboBox_Sunits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "Second", "Minute", "Hour", "Day", "Week", "Month" }));
        jComboBox_Sunits.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_SunitsItemStateChanged(evt);
            }
        });

        re_TextField.setEditable(false);

        funits_Label.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        funits_Label.setText("UNITS");

        sunits_Label.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        sunits_Label.setText("UNITS");

        back_Button.setText("Back");
        back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_ButtonActionPerformed(evt);
            }
        });

        exit_Button.setText("Exit");
        exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_ButtonActionPerformed(evt);
            }
        });

        convert_Button.setText("Converter");
        convert_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convert_ButtonActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.lightGray, null, java.awt.Color.lightGray));

        jLabel5.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        jLabel5.setText("FORMULAR :");

        formular_Label.setFont(new java.awt.Font("SimSun", 0, 16)); // NOI18N
        formular_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formular_Label.setText("FORMULAR");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(262, Short.MAX_VALUE))
            .addComponent(formular_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(formular_Label)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(funits_Label)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jComboBox_Funits, 0, 200, Short.MAX_VALUE)
                        .addComponent(in_TextField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox_Sunits, 0, 200, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(re_TextField))
                    .addComponent(sunits_Label, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(convert_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(exit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Funits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Sunits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funits_Label)
                    .addComponent(sunits_Label))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_Button)
                    .addComponent(convert_Button)
                    .addComponent(exit_Button))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_ButtonActionPerformed
        MainGUI goback = new MainGUI();
        goback.setVisible(true);
        goback.setAlwaysOnTop(true);
    }//GEN-LAST:event_back_ButtonActionPerformed

    private void exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_ButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit_ButtonActionPerformed

    private void convert_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convert_ButtonActionPerformed
        double in_value = Double.parseDouble(in_TextField.getText());
        double result = 0;

        if(jComboBox_Funits.getSelectedItem().toString() == "Second" && jComboBox_Sunits.getSelectedItem().toString() == "Second"){
            result = in_value;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Second" && jComboBox_Sunits.getSelectedItem().toString() == "Minute"){
            result = in_value / 60;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Second" && jComboBox_Sunits.getSelectedItem().toString() == "Hour"){
            result = in_value / 3600;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Second" && jComboBox_Sunits.getSelectedItem().toString() == "Day"){
            result = in_value / 1440;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Second" && jComboBox_Sunits.getSelectedItem().toString() == "Week"){
            result = in_value / 10080;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Second" && jComboBox_Sunits.getSelectedItem().toString() == "Month"){
            result = in_value / 43800;
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Minute" && jComboBox_Sunits.getSelectedItem().toString() == "Second"){
            result = in_value * 60;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Minute" && jComboBox_Sunits.getSelectedItem().toString() == "Minute"){
            result = in_value;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Minute" && jComboBox_Sunits.getSelectedItem().toString() == "Hour"){
            result = in_value / 60;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Minute" && jComboBox_Sunits.getSelectedItem().toString() == "Day"){
            result = in_value / 1440;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Minute" && jComboBox_Sunits.getSelectedItem().toString() == "Week"){
            result = in_value / 10080;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Minute" && jComboBox_Sunits.getSelectedItem().toString() == "Month"){
            result = in_value / 43800;
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Hour" && jComboBox_Sunits.getSelectedItem().toString() == "Second"){
            result = in_value * 3600;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Hour" && jComboBox_Sunits.getSelectedItem().toString() == "Minute"){
            result = in_value * 60;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Hour" && jComboBox_Sunits.getSelectedItem().toString() == "Hour"){
            result = in_value;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Hour" && jComboBox_Sunits.getSelectedItem().toString() == "Day"){
            result = in_value / 24;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Hour" && jComboBox_Sunits.getSelectedItem().toString() == "Week"){
            result = in_value / 168;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Hour" && jComboBox_Sunits.getSelectedItem().toString() == "Month"){
            result = in_value / 730;
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Day" && jComboBox_Sunits.getSelectedItem().toString() == "Second"){
            result = in_value * 86400;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Day" && jComboBox_Sunits.getSelectedItem().toString() == "Minute"){
            result = in_value * 1440;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Day" && jComboBox_Sunits.getSelectedItem().toString() == "Hour"){
            result = in_value * 24;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Day" && jComboBox_Sunits.getSelectedItem().toString() == "Day"){
            result = in_value;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Day" && jComboBox_Sunits.getSelectedItem().toString() == "Week"){
            result = in_value / 7;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Day" && jComboBox_Sunits.getSelectedItem().toString() == "Month"){
            result = in_value / 30.417;
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Week" && jComboBox_Sunits.getSelectedItem().toString() == "Second"){
            result = in_value * 604800;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Week" && jComboBox_Sunits.getSelectedItem().toString() == "Minute"){
            result = in_value * 10080;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Week" && jComboBox_Sunits.getSelectedItem().toString() == "Hour"){
            result = in_value * 168;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Week" && jComboBox_Sunits.getSelectedItem().toString() == "Day"){
            result = in_value * 7;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Week" && jComboBox_Sunits.getSelectedItem().toString() == "Week"){
            result = in_value;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Week" && jComboBox_Sunits.getSelectedItem().toString() == "Month"){
            result = in_value / 4.345;
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Month" && jComboBox_Sunits.getSelectedItem().toString() == "Second"){
            result = in_value * 2.628000000;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Month" && jComboBox_Sunits.getSelectedItem().toString() == "Minute"){
            result = in_value * 43800;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Month" && jComboBox_Sunits.getSelectedItem().toString() == "Hour"){
            result = in_value * 730;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Month" && jComboBox_Sunits.getSelectedItem().toString() == "Day"){
            result = in_value * 30.4167;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Month" && jComboBox_Sunits.getSelectedItem().toString() == "Week"){
            result = in_value * 4.34524;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Month" && jComboBox_Sunits.getSelectedItem().toString() == "Month"){
            result = in_value;
        }else{
             System.out.println("ERROR - PLEASE RESTART THE PROGRAM");
             er_start.setAlwaysOnTop(true);
             er_start.setVisible(true);
        }

        re_TextField.setText(new DecimalFormat("0.00000").format(result));
    }//GEN-LAST:event_convert_ButtonActionPerformed

    private void jComboBox_FunitsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_FunitsItemStateChanged
       int position = jComboBox_Funits.getSelectedIndex();
       funits_Label.setText(time_units[position]);
        
        if(jComboBox_Funits.getSelectedItem().toString() == "Second" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
             formular_Label.setText(time_formular[0]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Second" && jComboBox_Sunits.getSelectedItem().toString() == "Second"){
             formular_Label.setText(time_formular[1]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Second" && jComboBox_Sunits.getSelectedItem().toString() == "Minute"){
             formular_Label.setText(time_formular[2]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Second" && jComboBox_Sunits.getSelectedItem().toString() == "Hour"){
             formular_Label.setText(time_formular[3]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Second" && jComboBox_Sunits.getSelectedItem().toString() == "Day"){
             formular_Label.setText(time_formular[4]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Second" && jComboBox_Sunits.getSelectedItem().toString() == "Week"){
             formular_Label.setText(time_formular[5]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Second" && jComboBox_Sunits.getSelectedItem().toString() == "Month"){
             formular_Label.setText(time_formular[6]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Minute" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
             formular_Label.setText(time_formular[7]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Minute" && jComboBox_Sunits.getSelectedItem().toString() == "Second"){
             formular_Label.setText(time_formular[8]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Minute" && jComboBox_Sunits.getSelectedItem().toString() == "Minute"){
             formular_Label.setText(time_formular[9]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Minute" && jComboBox_Sunits.getSelectedItem().toString() == "Hour"){
             formular_Label.setText(time_formular[10]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Minute" && jComboBox_Sunits.getSelectedItem().toString() == "Day"){
             formular_Label.setText(time_formular[11]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Minute" && jComboBox_Sunits.getSelectedItem().toString() == "Week"){
             formular_Label.setText(time_formular[12]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Minute" && jComboBox_Sunits.getSelectedItem().toString() == "Month"){
             formular_Label.setText(time_formular[13]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Hour" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
             formular_Label.setText(time_formular[14]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Hour" && jComboBox_Sunits.getSelectedItem().toString() == "Second"){
             formular_Label.setText(time_formular[15]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Hour" && jComboBox_Sunits.getSelectedItem().toString() == "Minute"){
             formular_Label.setText(time_formular[16]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Hour" && jComboBox_Sunits.getSelectedItem().toString() == "Hour"){
             formular_Label.setText(time_formular[17]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Hour" && jComboBox_Sunits.getSelectedItem().toString() == "Day"){
             formular_Label.setText(time_formular[18]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Hour" && jComboBox_Sunits.getSelectedItem().toString() == "Week"){
             formular_Label.setText(time_formular[19]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Hour" && jComboBox_Sunits.getSelectedItem().toString() == "Month"){
             formular_Label.setText(time_formular[20]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Day" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
             formular_Label.setText(time_formular[21]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Day" && jComboBox_Sunits.getSelectedItem().toString() == "Second"){
             formular_Label.setText(time_formular[22]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Day" && jComboBox_Sunits.getSelectedItem().toString() == "Minute"){
             formular_Label.setText(time_formular[23]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Day" && jComboBox_Sunits.getSelectedItem().toString() == "Hour"){
             formular_Label.setText(time_formular[24]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Day" && jComboBox_Sunits.getSelectedItem().toString() == "Day"){
             formular_Label.setText(time_formular[25]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Day" && jComboBox_Sunits.getSelectedItem().toString() == "Week"){
             formular_Label.setText(time_formular[26]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Day" && jComboBox_Sunits.getSelectedItem().toString() == "Month"){
             formular_Label.setText(time_formular[27]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Week" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
             formular_Label.setText(time_formular[28]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Week" && jComboBox_Sunits.getSelectedItem().toString() == "Second"){
             formular_Label.setText(time_formular[29]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Week" && jComboBox_Sunits.getSelectedItem().toString() == "Minute"){
             formular_Label.setText(time_formular[30]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Week" && jComboBox_Sunits.getSelectedItem().toString() == "Hour"){
             formular_Label.setText(time_formular[31]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Week" && jComboBox_Sunits.getSelectedItem().toString() == "Day"){
             formular_Label.setText(time_formular[32]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Week" && jComboBox_Sunits.getSelectedItem().toString() == "Week"){
             formular_Label.setText(time_formular[33]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Week" && jComboBox_Sunits.getSelectedItem().toString() == "Month"){
             formular_Label.setText(time_formular[34]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Month" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
             formular_Label.setText(time_formular[35]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Month" && jComboBox_Sunits.getSelectedItem().toString() == "Second"){
             formular_Label.setText(time_formular[36]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Month" && jComboBox_Sunits.getSelectedItem().toString() == "Minute"){
             formular_Label.setText(time_formular[37]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Month" && jComboBox_Sunits.getSelectedItem().toString() == "Hour"){
             formular_Label.setText(time_formular[38]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Month" && jComboBox_Sunits.getSelectedItem().toString() == "Day"){
             formular_Label.setText(time_formular[39]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Month" && jComboBox_Sunits.getSelectedItem().toString() == "Week"){
             formular_Label.setText(time_formular[40]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Month" && jComboBox_Sunits.getSelectedItem().toString() == "Month"){
             formular_Label.setText(time_formular[41]);
        }else{
             System.out.println("ERROR - PLEASE RESTART THE PROGRAM");
        }
        
    }//GEN-LAST:event_jComboBox_FunitsItemStateChanged

    private void jComboBox_SunitsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_SunitsItemStateChanged
       int position = jComboBox_Sunits.getSelectedIndex();
       sunits_Label.setText(time_units[position]);
       
if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Second"){
             formular_Label.setText(time_formular[0]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Second" && jComboBox_Sunits.getSelectedItem().toString() == "Second"){
             formular_Label.setText(time_formular[1]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Second" && jComboBox_Sunits.getSelectedItem().toString() == "Minute"){
             formular_Label.setText(time_formular[2]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Second" && jComboBox_Sunits.getSelectedItem().toString() == "Hour"){
             formular_Label.setText(time_formular[3]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Second" && jComboBox_Sunits.getSelectedItem().toString() == "Day"){
             formular_Label.setText(time_formular[4]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Second" && jComboBox_Sunits.getSelectedItem().toString() == "Week"){
             formular_Label.setText(time_formular[5]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Second" && jComboBox_Sunits.getSelectedItem().toString() == "Month"){
             formular_Label.setText(time_formular[6]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Minute"){
             formular_Label.setText(time_formular[7]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Minute" && jComboBox_Sunits.getSelectedItem().toString() == "Second"){
             formular_Label.setText(time_formular[8]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Minute" && jComboBox_Sunits.getSelectedItem().toString() == "Minute"){
             formular_Label.setText(time_formular[9]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Minute" && jComboBox_Sunits.getSelectedItem().toString() == "Hour"){
             formular_Label.setText(time_formular[10]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Minute" && jComboBox_Sunits.getSelectedItem().toString() == "Day"){
             formular_Label.setText(time_formular[11]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Minute" && jComboBox_Sunits.getSelectedItem().toString() == "Week"){
             formular_Label.setText(time_formular[12]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Minute" && jComboBox_Sunits.getSelectedItem().toString() == "Month"){
             formular_Label.setText(time_formular[13]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Hour"){
             formular_Label.setText(time_formular[14]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Hour" && jComboBox_Sunits.getSelectedItem().toString() == "Second"){
             formular_Label.setText(time_formular[15]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Hour" && jComboBox_Sunits.getSelectedItem().toString() == "Minute"){
             formular_Label.setText(time_formular[16]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Hour" && jComboBox_Sunits.getSelectedItem().toString() == "Hour"){
             formular_Label.setText(time_formular[17]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Hour" && jComboBox_Sunits.getSelectedItem().toString() == "Day"){
             formular_Label.setText(time_formular[18]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Hour" && jComboBox_Sunits.getSelectedItem().toString() == "Week"){
             formular_Label.setText(time_formular[19]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Hour" && jComboBox_Sunits.getSelectedItem().toString() == "Month"){
             formular_Label.setText(time_formular[20]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Day"){
             formular_Label.setText(time_formular[21]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Day" && jComboBox_Sunits.getSelectedItem().toString() == "Second"){
             formular_Label.setText(time_formular[22]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Day" && jComboBox_Sunits.getSelectedItem().toString() == "Minute"){
             formular_Label.setText(time_formular[23]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Day" && jComboBox_Sunits.getSelectedItem().toString() == "Hour"){
             formular_Label.setText(time_formular[24]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Day" && jComboBox_Sunits.getSelectedItem().toString() == "Day"){
             formular_Label.setText(time_formular[25]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Day" && jComboBox_Sunits.getSelectedItem().toString() == "Week"){
             formular_Label.setText(time_formular[26]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Day" && jComboBox_Sunits.getSelectedItem().toString() == "Month"){
             formular_Label.setText(time_formular[27]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Week"){
             formular_Label.setText(time_formular[28]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Week" && jComboBox_Sunits.getSelectedItem().toString() == "Second"){
             formular_Label.setText(time_formular[29]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Week" && jComboBox_Sunits.getSelectedItem().toString() == "Minute"){
             formular_Label.setText(time_formular[30]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Week" && jComboBox_Sunits.getSelectedItem().toString() == "Hour"){
             formular_Label.setText(time_formular[31]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Week" && jComboBox_Sunits.getSelectedItem().toString() == "Day"){
             formular_Label.setText(time_formular[32]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Week" && jComboBox_Sunits.getSelectedItem().toString() == "Week"){
             formular_Label.setText(time_formular[33]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Week" && jComboBox_Sunits.getSelectedItem().toString() == "Month"){
             formular_Label.setText(time_formular[34]);
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Month"){
             formular_Label.setText(time_formular[35]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Month" && jComboBox_Sunits.getSelectedItem().toString() == "Second"){
             formular_Label.setText(time_formular[36]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Month" && jComboBox_Sunits.getSelectedItem().toString() == "Minute"){
             formular_Label.setText(time_formular[37]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Month" && jComboBox_Sunits.getSelectedItem().toString() == "Hour"){
             formular_Label.setText(time_formular[38]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Month" && jComboBox_Sunits.getSelectedItem().toString() == "Day"){
             formular_Label.setText(time_formular[39]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Month" && jComboBox_Sunits.getSelectedItem().toString() == "Week"){
             formular_Label.setText(time_formular[40]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Month" && jComboBox_Sunits.getSelectedItem().toString() == "Month"){
             formular_Label.setText(time_formular[41]);
        }else{
             System.out.println("ERROR - PLEASE RESTART THE PROGRAM");
        }

       
    }//GEN-LAST:event_jComboBox_SunitsItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Time_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Time_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Time_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Time_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Time_ConverterGUI().setVisible(true);
                new Time_ConverterGUI().setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_Button;
    private javax.swing.JButton convert_Button;
    private javax.swing.JButton exit_Button;
    private javax.swing.JLabel formular_Label;
    private javax.swing.JLabel funits_Label;
    private javax.swing.JTextField in_TextField;
    private javax.swing.JComboBox<String> jComboBox_Funits;
    private javax.swing.JComboBox<String> jComboBox_Sunits;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField re_TextField;
    private javax.swing.JLabel sunits_Label;
    // End of variables declaration//GEN-END:variables
}
