/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package units_converter_program;

import java.text.DecimalFormat;

/**
 *
 * @author Surachai
 */
public class Volume_ConverterGUI extends javax.swing.JFrame {

    Volume_ERROR er_start = new Volume_ERROR();
    String[] volume_units = {
      "UNITS" , "Liter (L.)" , "Milliliter (mL.)" , "Cubic meter (m³)" , "Cubic foot (ft³)" , "Cubic inch (in³)"
    };
    
    String[] volume_formular = {
        "None" ,                                           //0
        "None" ,                                           //1
        "Multiply the volume value by 1000" ,              //2
        "Divide the volume value by 1000" ,                //3
        "Divide the volume value by 28.317" ,              //4
        "Multiply the volume value by 61.024",             //5
        
        "None" ,                                           //6
        "Divide the volume value by 1000" ,                //7
        "None" ,                                           //8
        "Divide the volume value by 1e+6" ,                //9
        "Divide the volume value by 28317" ,               //10
        "Divide the volume value by 16.387",               //11
        
        "None" ,                                           //12
        "Multiply the volume value by 1000" ,              //13
        "Multiply the volume value by 1e+6" ,              //14
        "None" ,                                           //15
        "Multiply the volume value by 35.315" ,            //16
        "Multiply the volume value by 61024",              //17         
        
        "None" ,                                           //18
        "Multiply the volume value by 28.317" ,            //19
        "Multiply the volume value by 28317" ,             //20
        "Divide the volume value by 35.315" ,              //21
        "None" ,                                           //22
        "Multiply the volume value by 1728" ,              //23
        
        "None",                                            //24
        "Divide the volume value by 61.024",               //25
        "Multiply the volume value by 16.387",             //26
        "Divide the volume value by 61024",                //27
        "Divide the volume value by 1728",                 //28
        "None",                                            //29
        "None",                                            //30
        
    };
    public Volume_ConverterGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_Funits = new javax.swing.JComboBox<>();
        jComboBox_Sunits = new javax.swing.JComboBox<>();
        in_TextField = new javax.swing.JTextField();
        re_TextField = new javax.swing.JTextField();
        funits_Label = new javax.swing.JLabel();
        sunits_Label = new javax.swing.JLabel();
        back_Button = new javax.swing.JButton();
        exit_Button = new javax.swing.JButton();
        convert_Button = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        formular_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel1.setText("Volume Units Converter");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(216, 216, 216))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel3.setText("From volume unit of");

        jLabel4.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        jLabel4.setText("To volume unit of");

        jComboBox_Funits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "Liter", "Milliliter", "Cubic meter", "Cubic foot", "Cubic inch", " " }));
        jComboBox_Funits.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_FunitsItemStateChanged(evt);
            }
        });

        jComboBox_Sunits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "Liter", "Milliliter", "Cubic meter", "Cubic foot", "Cubic inch", " ", " " }));
        jComboBox_Sunits.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_SunitsItemStateChanged(evt);
            }
        });

        funits_Label.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        funits_Label.setText("UNITS");

        sunits_Label.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        sunits_Label.setText("UNITS");

        back_Button.setText("Back");
        back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_ButtonActionPerformed(evt);
            }
        });

        exit_Button.setText("Exit");
        exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_ButtonActionPerformed(evt);
            }
        });

        convert_Button.setText("Converter");
        convert_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convert_ButtonActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.lightGray, null, java.awt.Color.lightGray));

        jLabel5.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        jLabel5.setText("FORMULAR :");

        formular_Label.setFont(new java.awt.Font("SimSun", 0, 16)); // NOI18N
        formular_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formular_Label.setText("FORMULAR");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(262, Short.MAX_VALUE))
            .addComponent(formular_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(formular_Label)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(funits_Label)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jComboBox_Funits, 0, 200, Short.MAX_VALUE)
                        .addComponent(in_TextField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox_Sunits, 0, 200, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(re_TextField))
                    .addComponent(sunits_Label, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(convert_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(exit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Funits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Sunits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funits_Label)
                    .addComponent(sunits_Label))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_Button)
                    .addComponent(convert_Button)
                    .addComponent(exit_Button))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_ButtonActionPerformed
        MainGUI goback = new MainGUI();
        goback.setVisible(true);
        goback.setAlwaysOnTop(true);
    }//GEN-LAST:event_back_ButtonActionPerformed

    private void exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_ButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit_ButtonActionPerformed

    private void convert_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convert_ButtonActionPerformed
        double in_value = Double.parseDouble(in_TextField.getText());
        double result = 0;

        if(jComboBox_Funits.getSelectedItem().toString() == "Liter" && jComboBox_Sunits.getSelectedItem().toString() == "Liter"){
            result = in_value;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Liter" && jComboBox_Sunits.getSelectedItem().toString() == "Milliliter"){
            result = in_value * 1000;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Liter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic meter"){
            result = in_value / 1000;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Liter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic foot"){
            result = in_value / 28.317;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Liter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic inch"){
            result = in_value * 61.024;
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Milliliter" && jComboBox_Sunits.getSelectedItem().toString() == "Liter"){
            result = in_value / 1000;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Milliliter" && jComboBox_Sunits.getSelectedItem().toString() == "Milliliter"){
            result = in_value;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Milliliter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic meter"){
            result = in_value / 1000000;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Milliliter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic foot"){
            result = in_value / 28317;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Milliliter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic inch"){
            result = in_value / 16.387;
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic meter" && jComboBox_Sunits.getSelectedItem().toString() == "Liter"){
            result = in_value * 1000;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic meter" && jComboBox_Sunits.getSelectedItem().toString() == "Milliliter"){
            result = in_value * 1000000;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic meter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic meter"){
            result = in_value;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic meter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic foot"){
            result = in_value * 35.315;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic meter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic inch"){
            result = in_value * 61024;
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic foot" && jComboBox_Sunits.getSelectedItem().toString() == "Liter"){
            result = in_value * 28.317;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic foot" && jComboBox_Sunits.getSelectedItem().toString() == "Milliliter"){
            result = in_value * 28317;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic foot" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic meter"){
            result = in_value / 35.315;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic foot" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic foot"){
            result = in_value;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic foot" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic inch"){
            result = in_value * 1728;
        }
        
        else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic inch" && jComboBox_Sunits.getSelectedItem().toString() == "Liter"){
            result = in_value / 61.024;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic inch" && jComboBox_Sunits.getSelectedItem().toString() == "Milliliter"){
            result = in_value * 16.387;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic inch" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic meter"){
            result = in_value / 61024;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic inch" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic foot"){
            result = in_value / 1728;
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic inch" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic inch"){
            result = in_value;
        }else{
             System.out.println("ERROR - PLEASE RESTART THE PROGRAM");
             er_start.setAlwaysOnTop(true);
             er_start.setVisible(true);
        }
        
        

        re_TextField.setText(new DecimalFormat("0.000").format(result));
    }//GEN-LAST:event_convert_ButtonActionPerformed

    private void jComboBox_FunitsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_FunitsItemStateChanged
       int position = jComboBox_Funits.getSelectedIndex();
       funits_Label.setText(volume_units[position]);
       
       if(jComboBox_Funits.getSelectedItem().toString() == "Liter" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
            formular_Label.setText(volume_formular[0]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Liter" && jComboBox_Sunits.getSelectedItem().toString() == "Liter"){
            formular_Label.setText(volume_formular[1]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Liter" && jComboBox_Sunits.getSelectedItem().toString() == "Milliliter"){
            formular_Label.setText(volume_formular[2]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Liter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic meter"){
            formular_Label.setText(volume_formular[3]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Liter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic foot"){
            formular_Label.setText(volume_formular[4]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Liter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic inch"){
            formular_Label.setText(volume_formular[5]);
        }
       
        else if(jComboBox_Funits.getSelectedItem().toString() == "Milliliter" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
            formular_Label.setText(volume_formular[6]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Milliliter" && jComboBox_Sunits.getSelectedItem().toString() == "Liter"){
            formular_Label.setText(volume_formular[7]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Milliliter" && jComboBox_Sunits.getSelectedItem().toString() == "Milliliter"){
            formular_Label.setText(volume_formular[8]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Milliliter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic meter"){
            formular_Label.setText(volume_formular[9]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Milliliter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic foot"){
            formular_Label.setText(volume_formular[10]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Milliliter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic inch"){
            formular_Label.setText(volume_formular[11]);
        }
       
        else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic meter" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
            formular_Label.setText(volume_formular[12]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic meter" && jComboBox_Sunits.getSelectedItem().toString() == "Liter"){
            formular_Label.setText(volume_formular[13]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic meter" && jComboBox_Sunits.getSelectedItem().toString() == "Milliliter"){
            formular_Label.setText(volume_formular[14]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic meter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic meter"){
            formular_Label.setText(volume_formular[15]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic meter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic foot"){
            formular_Label.setText(volume_formular[16]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic meter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic inch"){
            formular_Label.setText(volume_formular[17]);
        }
       
        else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic foot" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
            formular_Label.setText(volume_formular[18]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic foot" && jComboBox_Sunits.getSelectedItem().toString() == "Liter"){
            formular_Label.setText(volume_formular[19]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic foot" && jComboBox_Sunits.getSelectedItem().toString() == "Milliliter"){
            formular_Label.setText(volume_formular[20]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic foot" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic meter"){
            formular_Label.setText(volume_formular[21]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic foot" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic foot"){
            formular_Label.setText(volume_formular[22]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic foot" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic inch"){
            formular_Label.setText(volume_formular[23]);
        }
       
        else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic inch" && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
            formular_Label.setText(volume_formular[24]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic inch" && jComboBox_Sunits.getSelectedItem().toString() == "Liter"){
            formular_Label.setText(volume_formular[25]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic inch" && jComboBox_Sunits.getSelectedItem().toString() == "Milliliter"){
            formular_Label.setText(volume_formular[26]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic inch" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic meter"){
            formular_Label.setText(volume_formular[27]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic inch" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic foot"){
            formular_Label.setText(volume_formular[28]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic inch" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic inch"){
            formular_Label.setText(volume_formular[29]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
            formular_Label.setText(volume_formular[30]);
        }
       
    }//GEN-LAST:event_jComboBox_FunitsItemStateChanged

    private void jComboBox_SunitsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_SunitsItemStateChanged
       int position = jComboBox_Sunits.getSelectedIndex();
       sunits_Label.setText(volume_units[position]);
       
       if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Liter"){
            formular_Label.setText(volume_formular[0]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Liter" && jComboBox_Sunits.getSelectedItem().toString() == "Liter"){
            formular_Label.setText(volume_formular[1]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Liter" && jComboBox_Sunits.getSelectedItem().toString() == "Milliliter"){
            formular_Label.setText(volume_formular[2]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Liter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic meter"){
            formular_Label.setText(volume_formular[3]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Liter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic foot"){
            formular_Label.setText(volume_formular[4]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Liter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic inch"){
            formular_Label.setText(volume_formular[5]);
        }
       
        else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Milliliter"){
            formular_Label.setText(volume_formular[6]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Milliliter" && jComboBox_Sunits.getSelectedItem().toString() == "Liter"){
            formular_Label.setText(volume_formular[7]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Milliliter" && jComboBox_Sunits.getSelectedItem().toString() == "Milliliter"){
            formular_Label.setText(volume_formular[8]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Milliliter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic meter"){
            formular_Label.setText(volume_formular[9]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Milliliter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic foot"){
            formular_Label.setText(volume_formular[10]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Milliliter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic inch"){
            formular_Label.setText(volume_formular[11]);
        }
       
        else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Cubic meter"){
            formular_Label.setText(volume_formular[12]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic meter" && jComboBox_Sunits.getSelectedItem().toString() == "Liter"){
            formular_Label.setText(volume_formular[13]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic meter" && jComboBox_Sunits.getSelectedItem().toString() == "Milliliter"){
            formular_Label.setText(volume_formular[14]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic meter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic meter"){
            formular_Label.setText(volume_formular[15]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic meter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic foot"){
            formular_Label.setText(volume_formular[16]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic meter" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic inch"){
            formular_Label.setText(volume_formular[17]);
        }
       
        else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Cubic foot"){
            formular_Label.setText(volume_formular[18]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic foot" && jComboBox_Sunits.getSelectedItem().toString() == "Liter"){
            formular_Label.setText(volume_formular[19]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic foot" && jComboBox_Sunits.getSelectedItem().toString() == "Milliliter"){
            formular_Label.setText(volume_formular[20]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic foot" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic meter"){
            formular_Label.setText(volume_formular[21]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic foot" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic foot"){
            formular_Label.setText(volume_formular[22]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic foot" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic inch"){
            formular_Label.setText(volume_formular[23]);
        }
       
        else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Cubic inch"){
            formular_Label.setText(volume_formular[24]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic inch" && jComboBox_Sunits.getSelectedItem().toString() == "Liter"){
            formular_Label.setText(volume_formular[25]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic inch" && jComboBox_Sunits.getSelectedItem().toString() == "Milliliter"){
            formular_Label.setText(volume_formular[26]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic inch" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic meter"){
            formular_Label.setText(volume_formular[27]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic inch" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic foot"){
            formular_Label.setText(volume_formular[28]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Cubic inch" && jComboBox_Sunits.getSelectedItem().toString() == "Cubic inch"){
            formular_Label.setText(volume_formular[29]);
        }else if(jComboBox_Funits.getSelectedItem().toString() == "Choose one..." && jComboBox_Sunits.getSelectedItem().toString() == "Choose one..."){
            formular_Label.setText(volume_formular[30]);
        }
    }//GEN-LAST:event_jComboBox_SunitsItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Volume_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Volume_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Volume_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Volume_ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Volume_ConverterGUI().setVisible(true);
                new Volume_ConverterGUI().setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_Button;
    private javax.swing.JButton convert_Button;
    private javax.swing.JButton exit_Button;
    private javax.swing.JLabel formular_Label;
    private javax.swing.JLabel funits_Label;
    private javax.swing.JTextField in_TextField;
    private javax.swing.JComboBox<String> jComboBox_Funits;
    private javax.swing.JComboBox<String> jComboBox_Sunits;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField re_TextField;
    private javax.swing.JLabel sunits_Label;
    // End of variables declaration//GEN-END:variables
}
